# This resource can be used if btp-certificate-issuer exist in target cluster
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hdlf-api-certs
status:
spec:
  issuerRef:
    group: btp-certificate-issuer.btp.sap.com
    kind: Issuer
    name: btp-cert-svc-issuer
  literalSubject: >-
    <update with your CN, L, OU, O, C values>
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    rotationPolicy: Always
    size: 2048
  revisionHistoryLimit: 5
  secretName: hdlf-api-certs
  usages:
    - digital signature
    - key encipherment
    - client auth
