apiVersion: batch/v1
kind: Job
metadata:
  name: hdlf-api-test-debug-job
  labels:
    app: hdlf-api-test-debug
spec:
  ttlSecondsAfterFinished: 86400  # Delete job 24 hours after completion
  template:
    metadata:
      labels:
        app: hdlf-api-test-debug
        job-name: hdlf-api-test-debug-job  # Explicitly add job-name label
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: hdlf-api-test
        image: sfroee/hdlf-api-test@sha256:1d3194dc4931fc2ccc5fa826302bcf17a9c1215a7f4c5b9c51932466eaf952a6
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        command: ["python3", "/app/hdlf_api_perf_test.py"]
        env:
        - name: FILES_REST_API
          valueFrom:
            configMapKeyRef:
              name: hdlf-api-test-config
              key: files_rest_api
              optional: true
        - name: CONTAINER
          valueFrom:
            configMapKeyRef:
              name: hdlf-api-test-config
              key: container
              optional: true
        # Override the number of requests for debug mode - use a smaller batch
        - name: NUM_REQUESTS
          value: "10"
        # Enable debug mode
        - name: DEBUG
          value: "true"
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: certs-volume
          mountPath: /certs
          readOnly: true
        - name: results-volume
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: hdlf-api-test-config
      - name: certs-volume
        secret:
          secretName: hdlf-api-certs
      - name: results-volume
        persistentVolumeClaim:
          claimName: hdlf-api-test-results-pvc
      restartPolicy: Never
  backoffLimit: 3
