apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdlf-api-test-results-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: default  # Adjust based on your K8s cluster's available storage classes
