apiVersion: v1
kind: Pod
metadata:
  name: results-reader
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  containers:
  - name: results-reader
    image: busybox:1.36
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    command: ["sleep", "3600"]  # Keep the pod running for 1 hour
    volumeMounts:
    - name: results-volume
      mountPath: /data
  volumes:
  - name: results-volume
    persistentVolumeClaim:
      claimName: hdlf-api-test-results-pvc
  restartPolicy: Never
