apiVersion: v1
kind: ConfigMap
metadata:
  name: hdlf-api-test-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "hdlf-api-test.labels" . | nindent 4 }}
data:
  files_rest_api: {{ .Values.hdlf.filesRestApi | quote }}
  container: {{ .Values.hdlf.container | quote }}
  num_requests: {{ .Values.hdlf.numRequests | quote }}
  debug: {{ .Values.hdlf.debug | quote }}
  file_path: {{ .Values.hdlf.filePath | quote }}
  test_type: {{ .Values.hdlf.testType | quote }}
  config.json: |
    {
      "files_rest_api": {{ .Values.hdlf.filesRestApi | quote }},
      "container": {{ .Values.hdlf.container | quote }},
      "crt_path": {{ .Values.hdlf.certPath | quote }},
      "key_path": {{ .Values.hdlf.keyPath | quote }},
      "num_requests": {{ .Values.hdlf.numRequests }},
      "port": {{ .Values.hdlf.port }},
      "output_path": {{ .Values.hdlf.outputPath | quote }},
      "debug": {{ .Values.hdlf.debug }},
      "file_path": {{ .Values.hdlf.filePath | quote }},
      "test_type": {{ .Values.hdlf.testType | quote }}
    }
