{{- if .Values.cronjob.create }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hdlf-api-test-cronjob
  labels:
    {{- include "hdlf-api-test.labels" . | nindent 4 }}
    app: hdlf-api-test
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
      template:
        metadata:
          labels:
            {{- include "hdlf-api-test.labels" . | nindent 12 }}
            app: hdlf-api-test
        spec:
          securityContext:
            runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            fsGroup: {{ .Values.securityContext.fsGroup }}
          containers:
          - name: hdlf-api-test
            image: {{ include "hdlf-api-test.image" . }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            securityContext:
              runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
              allowPrivilegeEscalation: {{ .Values.securityContext.container.allowPrivilegeEscalation }}
              capabilities:
                drop:
                {{- toYaml .Values.securityContext.container.capabilities.drop | nindent 18 }}
            resources:
              {{- toYaml .Values.job.resources | nindent 14 }}
            volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: certs-volume
              mountPath: /certs
              readOnly: true
            - name: results-volume
              mountPath: /data
            env:
            - name: FILES_REST_API
              valueFrom:
                configMapKeyRef:
                  name: hdlf-api-test-config
                  key: files_rest_api
                  optional: true
            - name: CONTAINER
              valueFrom:
                configMapKeyRef:
                  name: hdlf-api-test-config
                  key: container
                  optional: true
            - name: NUM_REQUESTS
              valueFrom:
                configMapKeyRef:
                  name: hdlf-api-test-config
                  key: num_requests
                  optional: true
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  name: hdlf-api-test-config
                  key: debug
                  optional: true
          volumes:
          - name: config-volume
            configMap:
              name: hdlf-api-test-config
          - name: certs-volume
            secret:
              secretName: hdlf-api-certs
          - name: results-volume
            persistentVolumeClaim:
              claimName: hdlf-api-test-results-pvc
          restartPolicy: Never
      backoffLimit: {{ .Values.job.backoffLimit }}
{{- end }}
