apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hdlf-api-test-results-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "hdlf-api-test.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
